Save and display diff
erwanlbp/trading-bot pull request #10
Opened 2024-03-31 21:32 UTC by AlexVcht

<img width="431" alt="image" src="https://github.com/erwanlbp/trading-bot/assets/29099155/91358874-9f3e-4658-ae66-6fa1f7672cf7">

2024-04-01 06:57 UTC, erwanlbp requested changes
💪 good first proposal 🏅small changes to make and some Go guidelines tips 🤏 continue to climb the ladder ! 🪜🚀🤘

2024-04-01 06:57 UTC, erwanlbp commented on cmd/balances/main.go
> +		fmt.Printf("%s -> %s : %s \n", m.FromCoin, m.ToCoin, m.Diff)
Arrondi à 2 chiffre

2024-04-01 06:57 UTC, erwanlbp commented on pkg/model/diff.go
> +	Diff      decimal.Decimal `gorm:"primaryKey"`
Pourquoi primary key sur la colonne diff ?

2024-04-01 06:57 UTC, erwanlbp commented on pkg/process/jump_finder.go
> +	p.Repository.ReplaceAllDiff(computedDiff)
Log un message de warning au moins si y'a une erreur, mais ouai ça doit pas être bloquant je suis d'accord

2024-04-01 06:57 UTC, erwanlbp commented on pkg/repository/diff.go
> +	"gorm.io/gorm"
En Go y'a une convention de lisibilité, qui n'est pas forcément appliquée par les linters des IDE par défaut, 
L'ordre des imports doit être :
<Les packages natifs (time, math, etc)>
<Saut de ligne>
<Les packages importés (zap logger, gorm, etc)>
<Les packages locaux (notre log, repository, db, process, etc)>

Une fois que tu l'as fait la première fois dans le fichier ton IDE devrait répertorier dans le bon groupe tes nouveaux imports

2024-04-01 06:57 UTC, erwanlbp commented on pkg/repository/diff.go
> +	return tx.Exec("DELETE FROM " + model.DiffTableName).Error
Tu as testé ? Je sais pas si Gorm il autorise ça par défaut, les delete sans where

2024-04-01 06:57 UTC, erwanlbp commented on pkg/repository/diff.go
> +			return fmt.Errorf("failed savec computed diff: %w", err)
Saving*

2024-04-01 06:57 UTC, erwanlbp commented on pkg/repository/diff.go
> +		r.Logger.Error(fmt.Sprintf("failed updating diff: %s", err))
J'aurais dit return juste l'erreur et laisse l'appelant la gérer comme il veut

2024-04-03 17:35 UTC, AlexVcht commented on pkg/repository/diff.go
> +	return tx.Exec("DELETE FROM " + model.DiffTableName).Error
Yep d'après la doc c'est si tu fais un .delete sans condition. Donc soit tu ajoutes un where 1 = 1 genre ou alors du sql 
<img width="819" alt="image" src="https://github.com/erwanlbp/trading-bot/assets/29099155/eb3b000e-2480-44ea-9ffb-d31fb7a54201">

2024-04-03 17:37 UTC, merged